cask "font-google-sans-flex" do
  version :latest
  sha256 :no_check

  url "https://github.com/bennetfabian/font-mirror.git",
      branch:    "main",
      only_path: "Google Sans Flex"
  name "Google Sans Flex"
  desc "Google Sans Flex is the next generation of Google’s brand typeface"
  homepage "https://fonts.google.com/specimen/Google+Sans+Flex"

  font "static/GoogleSansFlex_120pt-Black.ttf"
  font "static/GoogleSansFlex_120pt-Bold.ttf"
  font "static/GoogleSansFlex_120pt-ExtraBold.ttf"
  font "static/GoogleSansFlex_120pt-ExtraLight.ttf"
  font "static/GoogleSansFlex_120pt-Light.ttf"
  font "static/GoogleSansFlex_120pt-Medium.ttf"
  font "static/GoogleSansFlex_120pt-Regular.ttf"
  font "static/GoogleSansFlex_120pt-SemiBold.ttf"
  font "static/GoogleSansFlex_120pt-Thin.ttf"
  font "static/GoogleSansFlex_24pt-Black.ttf"
  font "static/GoogleSansFlex_24pt-Bold.ttf"
  font "static/GoogleSansFlex_24pt-ExtraBold.ttf"
  font "static/GoogleSansFlex_24pt-ExtraLight.ttf"
  font "static/GoogleSansFlex_24pt-Light.ttf"
  font "static/GoogleSansFlex_24pt-Medium.ttf"
  font "static/GoogleSansFlex_24pt-Regular.ttf"
  font "static/GoogleSansFlex_24pt-SemiBold.ttf"
  font "static/GoogleSansFlex_24pt-Thin.ttf"
  font "static/GoogleSansFlex_36pt-Black.ttf"
  font "static/GoogleSansFlex_36pt-Bold.ttf"
  font "static/GoogleSansFlex_36pt-ExtraBold.ttf"
  font "static/GoogleSansFlex_36pt-ExtraLight.ttf"
  font "static/GoogleSansFlex_36pt-Light.ttf"
  font "static/GoogleSansFlex_36pt-Medium.ttf"
  font "static/GoogleSansFlex_36pt-Regular.ttf"
  font "static/GoogleSansFlex_36pt-SemiBold.ttf"
  font "static/GoogleSansFlex_36pt-Thin.ttf"
  font "static/GoogleSansFlex_72pt-Black.ttf"
  font "static/GoogleSansFlex_72pt-Bold.ttf"
  font "static/GoogleSansFlex_72pt-ExtraBold.ttf"
  font "static/GoogleSansFlex_72pt-ExtraLight.ttf"
  font "static/GoogleSansFlex_72pt-Light.ttf"
  font "static/GoogleSansFlex_72pt-Medium.ttf"
  font "static/GoogleSansFlex_72pt-Regular.ttf"
  font "static/GoogleSansFlex_72pt-SemiBold.ttf"
  font "static/GoogleSansFlex_72pt-Thin.ttf"
  font "static/GoogleSansFlex_9pt-Black.ttf"
  font "static/GoogleSansFlex_9pt-Bold.ttf"
  font "static/GoogleSansFlex_9pt-ExtraBold.ttf"
  font "static/GoogleSansFlex_9pt-ExtraLight.ttf"
  font "static/GoogleSansFlex_9pt-Light.ttf"
  font "static/GoogleSansFlex_9pt-Medium.ttf"
  font "static/GoogleSansFlex_9pt-Regular.ttf"
  font "static/GoogleSansFlex_9pt-SemiBold.ttf"
  font "static/GoogleSansFlex_9pt-Thin.ttf"
end
