cask "font-open-sauce" do
  version :latest
  sha256 :no_check

  url "https://github.com/marcologous/Open-Sauce-Fonts/trunk/fonts",
      using: :svn
  name "Open Sauce"
  desc "Open Sauce typeface"
  homepage "https://github.com/marcologous/Open-Sauce-Fonts"

  font "OpenSauceOne-Black.ttf"
  font "OpenSauceOne-BlackItalic.ttf"
  font "OpenSauceOne-Bold.ttf"
  font "OpenSauceOne-BoldItalic.ttf"
  font "OpenSauceOne-ExtraBold.ttf"
  font "OpenSauceOne-ExtraBoldItalic.ttf"
  font "OpenSauceOne-Italic.ttf"
  font "OpenSauceOne-Light.ttf"
  font "OpenSauceOne-LightItalic.ttf"
  font "OpenSauceOne-Medium.ttf"
  font "OpenSauceOne-MediumItalic.ttf"
  font "OpenSauceOne-Regular.ttf"
  font "OpenSauceOne-SemiBold.ttf"
  font "OpenSauceOne-SemiBoldItalic.ttf"
  font "OpenSauceSans-Black.ttf"
  font "OpenSauceSans-BlackItalic.ttf"
  font "OpenSauceSans-Bold.ttf"
  font "OpenSauceSans-BoldItalic.ttf"
  font "OpenSauceSans-ExtraBold.ttf"
  font "OpenSauceSans-ExtraBoldItalic.ttf"
  font "OpenSauceSans-Italic.ttf"
  font "OpenSauceSans-Light.ttf"
  font "OpenSauceSans-LightItalic.ttf"
  font "OpenSauceSans-Medium.ttf"
  font "OpenSauceSans-MediumItalic.ttf"
  font "OpenSauceSans-Regular.ttf"
  font "OpenSauceSans-SemiBold.ttf"
  font "OpenSauceSans-SemiBoldItalic.ttf"
  font "OpenSauceTwo-Black.ttf"
  font "OpenSauceTwo-BlackItalic.ttf"
  font "OpenSauceTwo-Bold.ttf"
  font "OpenSauceTwo-BoldItalic.ttf"
  font "OpenSauceTwo-ExtraBold.ttf"
  font "OpenSauceTwo-ExtraBoldItalic.ttf"
  font "OpenSauceTwo-Italic.ttf"
  font "OpenSauceTwo-Light.ttf"
  font "OpenSauceTwo-LightItalic.ttf"
  font "OpenSauceTwo-Medium.ttf"
  font "OpenSauceTwo-MediumItalic.ttf"
  font "OpenSauceTwo-Regular.ttf"
  font "OpenSauceTwo-SemiBold.ttf"
  font "OpenSauceTwo-SemiBoldItalic.ttf"
end
