cask "font-shantell-sans" do
  version :latest
  sha256 :no_check

  url "https://github.com/arrowtype/shantell-sans/trunk/fonts/Shantell%20Sans/Desktop/Static/OTF",
      using: :svn
  name "Shantell Sans"
  desc "Shantell Sans typeface"
  homepage "https://github.com/arrowtype/shantell-sans"

  font "Shantell_Sans-Bouncy_Bold_Italic.otf"
  font "Shantell_Sans-Bouncy_Bold.otf"
  font "Shantell_Sans-Bouncy_ExtraBold_Italic.otf"
  font "Shantell_Sans-Bouncy_ExtraBold.otf"
  font "Shantell_Sans-Bouncy_Light_Italic.otf"
  font "Shantell_Sans-Bouncy_Light.otf"
  font "Shantell_Sans-Bouncy_Medium_Italic.otf"
  font "Shantell_Sans-Bouncy_Medium.otf"
  font "Shantell_Sans-Bouncy_Regular_Italic.otf"
  font "Shantell_Sans-Bouncy_Regular.otf"
  font "Shantell_Sans-Bouncy_SemiBold_Italic.otf"
  font "Shantell_Sans-Bouncy_SemiBold.otf"
  font "Shantell_Sans-Irregular_Bold_Italic.otf"
  font "Shantell_Sans-Irregular_Bold.otf"
  font "Shantell_Sans-Irregular_Bouncy_Bold_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_Bold.otf"
  font "Shantell_Sans-Irregular_Bouncy_ExtraBold_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_ExtraBold.otf"
  font "Shantell_Sans-Irregular_Bouncy_Light_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_Light.otf"
  font "Shantell_Sans-Irregular_Bouncy_Medium_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_Medium.otf"
  font "Shantell_Sans-Irregular_Bouncy_Regular_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_Regular.otf"
  font "Shantell_Sans-Irregular_Bouncy_SemiBold_Italic.otf"
  font "Shantell_Sans-Irregular_Bouncy_SemiBold.otf"
  font "Shantell_Sans-Irregular_ExtraBold_Italic.otf"
  font "Shantell_Sans-Irregular_ExtraBold.otf"
  font "Shantell_Sans-Irregular_Light_Italic.otf"
  font "Shantell_Sans-Irregular_Light.otf"
  font "Shantell_Sans-Irregular_Medium_Italic.otf"
  font "Shantell_Sans-Irregular_Medium.otf"
  font "Shantell_Sans-Irregular_Regular_Italic.otf"
  font "Shantell_Sans-Irregular_Regular.otf"
  font "Shantell_Sans-Irregular_SemiBold_Italic.otf"
  font "Shantell_Sans-Irregular_SemiBold.otf"
  font "Shantell_Sans-Normal-Bold_Italic.otf"
  font "Shantell_Sans-Normal-Bold.otf"
  font "Shantell_Sans-Normal-ExtraBold_Italic.otf"
  font "Shantell_Sans-Normal-ExtraBold.otf"
  font "Shantell_Sans-Normal-Light_Italic.otf"
  font "Shantell_Sans-Normal-Light.otf"
  font "Shantell_Sans-Normal-Medium_Italic.otf"
  font "Shantell_Sans-Normal-Medium.otf"
  font "Shantell_Sans-Normal-Regular_Italic.otf"
  font "Shantell_Sans-Normal-Regular.otf"
  font "Shantell_Sans-Normal-SemiBold_Italic.otf"
  font "Shantell_Sans-Normal-SemiBold.otf"
end
