cask "font-martian-grotesk" do
  version :latest
  sha256 :no_check

  url "https://github.com/evilmartians/grotesk",
      using:    :git,
      branch:   "main",
      only_path: "fonts/otf"
  name "Martian Grotesk"
  desc ""
  homepage "https://evilmartians.com/products/martian-grotesk"

  font "MartianGrotesk-CnBd.otf", target: "MartianGrotesk-Condensed-Bold.otf"
  font "MartianGrotesk-CnBl.otf", target: "MartianGrotesk-Condensed-Black.otf"
  font "MartianGrotesk-CnLt.otf", target: "MartianGrotesk-Condensed-Light.otf"
  font "MartianGrotesk-CnMd.otf", target: "MartianGrotesk-Condensed-Medium.otf"
  font "MartianGrotesk-CnRg.otf", target: "MartianGrotesk-Condensed-Regular.otf"
  font "MartianGrotesk-CnTh.otf", target: "MartianGrotesk-Condensed-Thin.otf"
  font "MartianGrotesk-CnUlt.otf", target: "MartianGrotesk-Condensed-UltraBlack.otf"
  font "MartianGrotesk-CnxBd.otf", target: "MartianGrotesk-Condensed-ExtraBold.otf"
  font "MartianGrotesk-CnxLt.otf", target: "MartianGrotesk-Condensed-ExtraLight.otf"
  font "MartianGrotesk-NrBd.otf", target: "MartianGrotesk-Narrow-Bold.otf"
  font "MartianGrotesk-NrBl.otf", target: "MartianGrotesk-Narrow-Black.otf"
  font "MartianGrotesk-NrLt.otf", target: "MartianGrotesk-Narrow-Light.otf"
  font "MartianGrotesk-NrMd.otf", target: "MartianGrotesk-Narrow-Medium.otf"
  font "MartianGrotesk-NrRg.otf", target: "MartianGrotesk-Narrow-Regular.otf"
  font "MartianGrotesk-NrTh.otf", target: "MartianGrotesk-Narrow-Thin.otf"
  font "MartianGrotesk-NrUlt.otf", target: "MartianGrotesk-Narrow-UltraBlack.otf"
  font "MartianGrotesk-NrxBd.otf", target: "MartianGrotesk-Narrow-ExtraBold.otf"
  font "MartianGrotesk-NrxLt.otf", target: "MartianGrotesk-Narrow-ExtraLight.otf"
  font "MartianGrotesk-StdBd.otf", target: "MartianGrotesk-Standard-Bold.otf"
  font "MartianGrotesk-StdBl.otf", target: "MartianGrotesk-Standard-Black.otf"
  font "MartianGrotesk-StdLt.otf", target: "MartianGrotesk-Standard-Light.otf"
  font "MartianGrotesk-StdMd.otf", target: "MartianGrotesk-Standard-Medium.otf"
  font "MartianGrotesk-StdRg.otf", target: "MartianGrotesk-Standard-Regular.otf"
  font "MartianGrotesk-StdTh.otf", target: "MartianGrotesk-Standard-Thin.otf"
  font "MartianGrotesk-StdUlt.otf", target: "MartianGrotesk-Standard-UltraBlack.otf"
  font "MartianGrotesk-StdxBd.otf", target: "MartianGrotesk-Standard-ExtraBold.otf"
  font "MartianGrotesk-StdxLt.otf", target: "MartianGrotesk-Standard-ExtraLight.otf"
  font "MartianGrotesk-WdBd.otf", target: "MartianGrotesk-Wide-Bold.otf"
  font "MartianGrotesk-WdBl.otf", target: "MartianGrotesk-Wide-Black.otf"
  font "MartianGrotesk-WdLt.otf", target: "MartianGrotesk-Wide-Light.otf"
  font "MartianGrotesk-WdMd.otf", target: "MartianGrotesk-Wide-Medium.otf"
  font "MartianGrotesk-WdRg.otf", target: "MartianGrotesk-Wide-Regular.otf"
  font "MartianGrotesk-WdTh.otf", target: "MartianGrotesk-Wide-Thin.otf"
  font "MartianGrotesk-WdUlt.otf", target: "MartianGrotesk-Wide-UltraBlack.otf"
  font "MartianGrotesk-WdxBd.otf", target: "MartianGrotesk-Wide-ExtraBold.otf"
  font "MartianGrotesk-WdxLt.otf", target: "MartianGrotesk-Wide-ExtraLight.otf"
  font "MartianGrotesk-sWdBd.otf", target: "MartianGrotesk-SemiWide-Bold.otf"
  font "MartianGrotesk-sWdBl.otf", target: "MartianGrotesk-SemiWide-Black.otf"
  font "MartianGrotesk-sWdLt.otf", target: "MartianGrotesk-SemiWide-Light.otf"
  font "MartianGrotesk-sWdMd.otf", target: "MartianGrotesk-SemiWide-Medium.otf"
  font "MartianGrotesk-sWdRg.otf", target: "MartianGrotesk-SemiWide-Regular.otf"
  font "MartianGrotesk-sWdTh.otf", target: "MartianGrotesk-SemiWide-Thin.otf"
  font "MartianGrotesk-sWdUlt.otf", target: "MartianGrotesk-SemiWide-UltraBlack.otf"
  font "MartianGrotesk-sWdxBd.otf", target: "MartianGrotesk-SemiWide-ExtraBold.otf"
  font "MartianGrotesk-sWdxLt.otf", target: "MartianGrotesk-SemiWide-ExtraLight.otf"
  font "MartianGrotesk-uWdBd.otf", target: "MartianGrotesk-UltraWide-Bold.otf"
  font "MartianGrotesk-uWdBl.otf", target: "MartianGrotesk-UltraWide-Black.otf"
  font "MartianGrotesk-uWdLt.otf", target: "MartianGrotesk-UltraWide-Light.otf"
  font "MartianGrotesk-uWdMd.otf", target: "MartianGrotesk-UltraWide-Medium.otf"
  font "MartianGrotesk-uWdRg.otf", target: "MartianGrotesk-UltraWide-Regular.otf"
  font "MartianGrotesk-uWdTh.otf", target: "MartianGrotesk-UltraWide-Thin.otf"
  font "MartianGrotesk-uWdUlt.otf", target: "MartianGrotesk-UltraWide-UltraBlack.otf"
  font "MartianGrotesk-uWdxBd.otf", target: "MartianGrotesk-UltraWide-ExtraBold.otf"
  font "MartianGrotesk-uWdxLt.otf", target: "MartianGrotesk-UltraWide-ExtraLight.otf"
  font "MartianGrotesk-xWdBd.otf", target: "MartianGrotesk-ExtraWide-Bold.otf"
  font "MartianGrotesk-xWdBl.otf", target: "MartianGrotesk-ExtraWide-Black.otf"
  font "MartianGrotesk-xWdLt.otf", target: "MartianGrotesk-ExtraWide-Light.otf"
  font "MartianGrotesk-xWdMd.otf", target: "MartianGrotesk-ExtraWide-Medium.otf"
  font "MartianGrotesk-xWdRg.otf", target: "MartianGrotesk-ExtraWide-Regular.otf"
  font "MartianGrotesk-xWdTh.otf", target: "MartianGrotesk-ExtraWide-Thin.otf"
  font "MartianGrotesk-xWdUlt.otf", target: "MartianGrotesk-ExtraWide-UltraBlack.otf"
  font "MartianGrotesk-xWdxBd.otf", target: "MartianGrotesk-ExtraWide-ExtraBold.otf"
  font "MartianGrotesk-xWdxLt.otf", target: "MartianGrotesk-ExtraWide-ExtraLight.otf"
end
